### ISSUE TITLE
How to download the data?

### ISSUE THREAD

**Issue by Bioinformaticslover** [getzlab/CLUMPS-PTM#2]
How can I download the file "RefSeq.20180629_Human_ucsc_hg38_cpdbnr_mito_264contams_553smORFs.fasta"?
Thank you very much!

**Comment by Ansanqi** [comment]
The authors presumably removed these data after publication

**Comment by shankara-a** [comment]
Hi - thank you for your question! Apologies for the delayed response. _CLUMPS-PTM_ can be used with any reference fasta, but the one used in the example file (referenced above) I will include in the paper directory for the [CPTAC Pan-Cancer project](https://github.com/getzlab/CPTAC_PanCan_PTM_2023) under **data**. Will upload this later today. Let me know if you have further questions!


Shankara
